name: storks_env
channels:
  - defaults
dependencies:
  - ansi2html=1.8.0
  - blas=1.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cycler=0.11.0
  - dash=2.14.2
  - flask=2.2.5
  - flask-compress=1.13
  - folium=0.14.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - geos=3.9.1
  - giflib=5.2.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.3.0
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.4
  - pillow=10.0.1
  - pip=23.3.1
  - plotly=5.9.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - retrying=1.3.3
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - typing_extensions=4.7.1
  - tzdata=2023d
  - urllib3=1.26.18
  - werkzeug=2.2.3
  - wheel=0.41.2
  - xz=5.4.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - attrs==23.2.0
      - click-plugins==1.1.1
      - cligj==0.7.2
      - fiona==1.9.5
      - geographiclib==2.0
      - geopandas==0.14.2
      - geopy==2.4.1
      - pyproj==3.6.1
      - shapely==2.0.2

